## Copyright (C) 2014 Marshall Farrier, Robert Rodrigues
##
## Distribution and use of this software without prior written permission
## of the authors is strictly prohibitied and will be prosecuted to
## the full extent of the law.

## -*- texinfo -*-
## @deftypefn  {Function File} {@var{features} =} getFeatures (@var{prices}, @var{interval}) 
## Generate a matrix of features from a matrix of prices and an interval.
##
## @var{features} is generated by concatenating @var{interval} rows of @var{prices}
##
## Example usage:
## X = getFeatures(prices, interval)
## @end deftypefn

## Author: mdf
## Created: 2014-06-18

function [features] = getFeatures(prices, interval)

m = size(prices, 1) - interval + 1;
pricecols = size(prices, 2);
featurecols = interval * pricecols;
features = zeros(m, featurecols);

for i = 1:m
    features(i, :) = vec(prices(i:i + interval - 1, :)', 2);
endfor

end
